### PR TITLE
Customers can change their mind mid-order

### PR DESCRIPTION
**Pull request by lauramasselos**
Few updates:
- More fluid / natural dialogue exchange between Albert and customer
- Customer can confirm or cancel what they've ordered and change their mind before finishing the intent
- If customer requests an item not on the menu, Albert prompts them to check the menu again and ask for something else

### CODE REVIEW

**Comment by Visgean** [comment]
Just a quick note: add project settings to git ignore

**Comment by Visgean** [comment]
can you merge current master into yours?

**Comment by lauramasselos** [comment]
All done!

**Comment by Visgean** [comment]
Nice, ready for merge!

**Pull request merged**
