### PR TITLE
Add new vision stuff

### PR DESCRIPTION
**Pull request by benjikershenbaum**

### CODE REVIEW

**Comment by Visgean** [comment]
@danielgritsevski can you please stop merging stuff?

**Comment by danielgritsevski** [comment]
@Visgean this was not work in progress, code is fine, codeship status is passing, no conflicts found, so why not to merge?

**Comment by Visgean** [comment]
because people (me) wanted to comment. Codeship has nothing to do with this code. But also code was not fine, it completely ignored all the refactoring changes that I have made, there are some problems with indentation...

**Comment by Visgean** [comment]
and FYI, i made this PR with benji's account.

**Comment by danielgritsevski** [comment]
Ok, then just write a comment next time when you are making PR with other people's accounts and write WIP. Then I will not merge it.

**Comment by Visgean** [comment]
do not merge before checking it is finished?

**Comment by danielgritsevski** [comment]
sounds reasonable

**Comment by Visgean** [comment]
Thanks!

**Pull request merged**
